trainer:
  name: Trainer
  num_epochs: 50

model:
  name: cifar_vit
  num_classes: 10
  image_size: 64
  pretrained_model: True

dataset:
  name: CIFAR10DataLoader
  root: ~/.wrt/data
  subset: defender
  batch_size: 128
  image_size: 64
  num_workers: 16

optimizer:
  name: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True

scheduler:
  name: MultiStepLR
  milestones: [20, 30, 40]
  gamma: 0.2


name: vit
output_dir: outputs/cifar10/null_models/vit/
