wm_scheme:
  name: wm_deepmarks
  layer_index: 0
  gamma: 10
  num_classes: 10

embed:
  name: wm_deepmarks_embed
  epochs: 60
  keylength: 100
  check_every_n_batches: 200
  patience: 5

source_model:
  name: cifar_wide_resnet
  image_size: 32
  num_classes: 10

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

dataset:
  name: CIFAR10DataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 128
  image_size: 32
  num_workers: 16

name: deepmarks
output_dir: outputs/cifar10/wm/deepmarks/


