wm_scheme:
  name: wm_deepsignwb
  layer_dim: 24576
  layer_index: 17
  gamma0: 1
  gamma1: 0.001
  gamma2: 0.3
  gamma3: 0
  mu_lr: 0.01
  embedding_rate: 10
  num_gaussians: 10
  from_scratch: False
  separate_means: False
  num_classes: 10

embed:
  name: wm_deepsignwb_embed
  keylength: 100
  epochs: 100
  check_every_n_batches: 200
  reduce_lr_by_factor: 10

source_model:
  name: cifar_vit
  image_size: 32
  num_classes: 10

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: CIFAR10DataLoader
  apply_augmentation: False
  download: False
  subset: defender
  shuffle: True
  train: True
  root: ~/.wrt/data
  batch_size: 128
  image_size: 32
  num_workers: 16

dataset:
  name: CIFAR10DataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 128
  image_size: 32
  num_workers: 16

name: deepsignwb
output_dir: outputs/cifar10/wm/deepsignwb/


