wm_scheme:
  name: wm_frontier_stitching
  eps: 0.01
  num_classes: 10

embed:
  name: wm_frontier_stitching_embed
  keylength: 100
  epochs: 60
  patience: 5
  boost_factor: 10
  batch_size: 128

source_model:
  name: cifar_vit
  image_size: 64
  num_classes: 10
  pretrained_model: True

optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: CIFAR10DataLoader
  apply_normalization: False
  apply_augmentation: False
  subset: defender
  train: True
  root: ~/.wrt/data
  batch_size: 64
  image_size: 64
  num_workers: 16

dataset:
  name: CIFAR10DataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 128
  image_size: 64
  num_workers: 16

name: frontier_stitching
output_dir: outputs/cifar10/wm/frontier_stitching_vit/


