wm_scheme:
  name: wm_jia
  snnl_weight: 64
  num_classes: 10
  alternating_rate: 2
  rate: 30
  trigger_width: 10
  trigger_height: 10
  pos: (0, 4, 4),

embed:
  name: wm_jia_embed
  epochs: 60
  keylength: 100
  embedding_keylength: 100
  reduced_lr_rate: 10.0
  source_class: 4
  target_class: 6
  check_every_n_batches: 200
  patience: 5

source_model:
  name: cifar_vit
  image_size: 64
  num_classes: 10
  pretrained_model: True

optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: CIFAR10DataLoader
  apply_normalization: False
  apply_augmentation: False
  class_labels: 4
  train: True
  subset: defender
  root: ~/.wrt/data
  batch_size: 64
  image_size: 64
  num_workers: 16

wm_dataset_target:
  name: CIFAR10DataLoader
  subset: defender
  apply_normalization: False
  apply_augmentation: False
  class_labels: 6
  train: True
  root: ~/.wrt/data
  batch_size: 64
  image_size: 64
  num_workers: 16

dataset:
  name: CIFAR10DataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 128
  image_size: 64
  num_workers: 16

name: jia
output_dir: outputs/cifar10/wm/jia_vit/


