wm_scheme:
  name: wm_noise
  std: 0.4
  num_classes: 10

embed:
  name: wm_noise_embed
  source_class: 4
  target_class: 6
  epochs: 60
  keylength: 100
  patience: 5
  decrease_lr_factor: 1
  boost_factor: 10

source_model:
  name: cifar_vit
  image_size: 32
  num_classes: 10

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: CIFAR10DataLoader
  apply_normalization: False
  apply_augmentation: False
  class_labels: 4
  train: True
  subset: defender
  root: ~/.wrt/data
  batch_size: 128
  image_size: 32
  num_workers: 16

dataset:
  name: CIFAR10DataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 128
  image_size: 32
  num_workers: 16

name: noise
output_dir: outputs/cifar10/wm/noise/


