wm_scheme:
  name: wm_unrelated
  num_classes: 10

embed:
  name: wm_unrelated_embed
  source_class: 4
  target_class: 6
  epochs: 60
  keylength: 100
  boost_factor: 10
  check_every_n_batches: 200
  patience: 5

source_model:
  name: cifar_vit
  image_size: 32
  num_classes: 10
  pretrained_model: True

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: OmniglotDataLoader
  apply_normalization: False
  apply_augmentation: False
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 16

dataset:
  name: CIFAR10DataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 128
  image_size: 32
  num_workers: 16

name: unrelated
output_dir: outputs/cifar10/wm/unrelated_vit/


