wm_scheme:
  name: wm_content
  pos: (0, 2, 2),
  size: 16
  num_classes: 10

embed:
  name: wm_content_embed
  source_class: 4
  target_class: 6
  epochs: 60
  patience: 5
  decrease_lr_factor: 1.0
  check_every_n_batches: 200
  keylength: 100
  boost_factor: 10

source_model:
  name: cifar_r50_vit
  image_size: 64
  num_classes: 10
  pretrained_model: True

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: CIFAR10DataLoader
  apply_normalization: False
  apply_augmentation: False
  class_labels: 4
  train: True
  subset: defender
  root: ~/.wrt/data
  batch_size: 64
  image_size: 64
  download: False
  num_workers: 16

dataset:
  name: CIFAR10DataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 128
  image_size: 64
  num_workers: 16
  download: False

name: content
output_dir: outputs/cifar10/wm/content_r50vit/


