create:
  name: knockoff_attack
  num_classes: 10

surrogate_model:
  name: cifar_wide_resnet_features
  image_size: 32
  num_classes: 10

remove:
  name: knockoff_removal
  epochs: 4

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2

transfer_dataset:
  name: FlatImagesDataLoader
  root: ~/.wrt/data/open_images
  apply_augmentation: False
  batch_size: 64
  image_size: 32
  num_workers: 16
  n_train: 1250000

optimizer:
  name: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: True

scheduler:
  name: MultiStepLR
  milestones: [1, 2, 3]
  gamma: 0.2

true_labels: True
name: knockoff
output_dir: outputs/cifar10/attacks/knockoff/