create:
  name: neural_cleanse_partial_unlearning_attack
  extract: True
  num_classes: 10
  extract_kwargs:
    extract_epochs: 4
    extract_steps: 10
    finetune_steps: 30
    finetune_epochs: 8
    lmbda: 0.05
    batch_size: 64

remove:
  name: neural_cleanse_partial_unlearning_removal
  epochs: 5

subset_dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2
  class_labels: [3, 4]

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  download: False
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: False
name: neural_cleanse_partial_unlearning1
output_dir: outputs/cifar10/attack_experiments/neural_cleanse_partial_unlearning1/
