create:
  name: label_smoothing_attack
  num_classes: 10

remove:
  name: label_smoothing_removal
  epochs: 5
  top_k: 3
  epsilon: 0.3

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  download: False
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: False
name: label_smoothing
output_dir: outputs/cifar10/attacks/label_smoothing/
