create:
  name: rtal_attack
  num_classes: 10

remove:
  name: rtal_removal
  epochs: 5

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2

scheduler:
  name: MultiStepLR
  milestones: [1,2,3]
  gamma: 0.1

optimizer:
  name: SGD
  lr: 0
  weight_decay: 0.0001
  momentum: 0.9

true_labels: False
name: rtal
output_dir: outputs/cifar10/attacks/rtal/
