wm_scheme:
  name: wm_jia
  snnl_weight: 1
  trigger_width: 10
  trigger_height: 10
  pos: (0, 4, 4),
  num_classes: 10

secret_keys:
  name: wm_jia_keygen
  image_size: 64
  num_classes: 10
  source_class: 4
  target_class: 6

source_model_architecture:
  name: cifar_wide_resnet_features
  image_size: 64
  num_classes: 10

null_model_architecture:
  name: cifar_wide_resnet
  image_size: 64
  num_classes: 10

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

null_models:
  name: load_null_models_resnet
  paths: ['outputs/cifar10/null_models_experiments/resnet/00000_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00001_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00002_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00003_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00004_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00005_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00006_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00007_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00010_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00011_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00012_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00013_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00014_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00015_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00016_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00017_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00018_null_model/best.pth',
          'outputs/cifar10/null_models_experiments/resnet/00019_null_model/best.pth',
  ]
  num_classes: 10
  image_size: 64

wm_dataset:
  name: CIFAR10DataLoader
  apply_normalization: False
  apply_augmentation: False
  train: False
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 64
  num_workers: 16

wm_dataset_target:
  name: CIFAR10ExtendedDataLoader
  subset: defender
  apply_normalization: False
  apply_augmentation: False
  train: True
  root: ~/.wrt/data
  batch_size: 64
  image_size: 64
  num_workers: 16

dataset:
  name: CIFAR10DataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 128
  image_size: 64
  num_workers: 16

name: jia
output_dir: outputs/cifar10/decision_thresholds/jia
