create:
  name: distillation_attack
  num_classes: 10
  T: 3
  alpha: 1.0

surrogate_model:
  name: cifar_vit
  image_size: 64
  num_classes: 10

remove:
  name: distillation_removal
  epochs: 60

dataset:
  name: CIFAR10DataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 64
  num_workers: 2
  apply_softmax: False

optimizer:
  name: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: True

scheduler:
  name: MultiStepLR
  milestones: [20, 35, 50]
  gamma: 0.2

true_labels: False
name: distillation
output_dir: outputs/cifar10/attacks/distillation/
